import { Link } from 'react-router-dom'
import PageShell, { Callout, Section } from '../components/PageShell'

export default function About() {
  return (
    <PageShell
      eyebrow="about"
      title="Why PathFinder exists"
      intro="Because “beta, science le lo” is not a career plan."
    >
      <Section title="The problem">
        <p>
          After Class 10 and Class 12, almost every student in India is asked to make a
          decision that shapes the next decade of their life — and handed almost nothing
          useful to make it with. The information exists, but it is scattered across coaching
          brochures, forum threads, YouTube videos of wildly varying quality, and relatives
          with strong opinions and no sources.
        </p>
        <p>
          What is missing is rarely more advice. It is the <em>order</em> of things: which
          stream, which exam, which degree, and what has to happen before what.
        </p>
      </Section>

      <Section title="What this does">
        <p>
          PathFinder takes two answers and turns them into one chronological path. You can
          start from either end:
        </p>
        <ul className="space-y-2 pl-5 list-disc marker:text-saffron">
          <li>
            <strong className="text-ink font-medium">You don&rsquo;t know what to pick.</strong>{' '}
            Tell it where you are and what you enjoy, and it suggests a direction with the
            route to get there.
          </li>
          <li>
            <strong className="text-ink font-medium">You already know the goal.</strong> Name
            the career and it works backwards to the stream you should choose now.
          </li>
        </ul>
        <p>
          Either way you get the steps in order, the exams to track, and the mistake people
          most often make on that particular route. You can save the whole thing as a PDF.
        </p>
      </Section>

      <Section title="How it works">
        <p>
          Your answers are sent to Google&rsquo;s Gemini model with instructions to ground
          every step in the real Indian education system — CBSE, ICSE and state boards, the
          Science/Commerce/Arts streams, and the actual entrance exams like JEE, NEET, CLAT,
          CUET, CA Foundation and the state CETs.
        </p>
        <p>
          There is no account, no sign-up and no database. The request goes straight from
          your browser, and nothing you type is stored. See the{' '}
          <Link to="/privacy" className="text-saffron underline underline-offset-2">
            Privacy Policy
          </Link>{' '}
          for the details.
        </p>
      </Section>

      <Callout tone="coral" title="What this is not">
        <p>
          This is a starting point, not a counsellor and not an authority. It is generated by
          an AI model, which means it can be confidently wrong — about a cutoff, a deadline,
          an eligibility rule, or an exam that changed format last year.
        </p>
        <p>
          Treat every roadmap as a map to check, not a instruction to follow. Confirm dates
          and eligibility against the official board, exam authority or college before you act
          on anything.
        </p>
      </Callout>

      <Section title="Who made it">
        <p>
          PathFinder is a small independent project, built because the problem was annoying
          enough to be worth fixing. It is free, has no ads today, and does not sell anything.
        </p>
        <p>
          Suggestions, corrections and “this step is wrong” emails are genuinely welcome —{' '}
          <Link to="/contact" className="text-saffron underline underline-offset-2">
            get in touch
          </Link>
          .
        </p>
      </Section>
    </PageShell>
  )
}
