import PageShell, { Callout, Section } from '../components/PageShell'
import ClearCacheButton from '../components/ClearCacheButton'
import { ANALYTICS_ENABLED, CONTACT_EMAIL, LAST_UPDATED } from '../siteConfig'

export default function Privacy() {
  return (
    <PageShell
      eyebrow="privacy policy"
      title="What we collect"
      intro="Short version: nothing. There is no account to make and no database to leak."
      meta={`Last updated ${LAST_UPDATED}`}
    >
      <Callout tone="teal" title="the whole thing in one line">
        <p>
          PathFinder has no sign-up, sets no cookies, and runs no server of its own. Your
          answers go from your browser straight to Google&rsquo;s Gemini API. We never receive
          them, and there is no database on our side for them to sit in.
        </p>
      </Callout>

      <Section title="Information you give us">
        <p>
          The only things you enter are your stage (Class 10 or 12), the interests you tick,
          or the career or courses you name. These are used to build the roadmap or comparison
          you asked for.
        </p>
        <p>
          They are never sent to us. There is no PathFinder server in the middle — the request
          goes from your own browser to Google&rsquo;s API and the answer comes back the same
          way. Nobody here can see what you searched for.
        </p>
      </Section>

      <Section title="Saved on your device">
        <p>
          To keep the site fast and avoid regenerating the same answer repeatedly, PathFinder
          saves the roadmaps and comparisons you generate in your browser&rsquo;s{' '}
          <strong className="text-ink font-medium">local storage</strong>. This is storage on
          your own device — it is not a cookie, it is not sent anywhere, and it is not visible
          to us or to anyone else.
        </p>
        <p>
          It holds the generated result and the question that produced it, capped at the 80
          most recent, and each entry expires automatically after 30 days so that outdated exam
          information is not served back to you indefinitely.
        </p>
        <p>
          You can wipe it at any time with the button below, or by clearing site data in your
          browser settings. Nothing breaks if you do — results are simply regenerated on demand.
        </p>
        <ClearCacheButton />
      </Section>

      <Section title="Information we collect automatically">
        <p>
          {ANALYTICS_ENABLED
            ? 'We use privacy-friendly analytics to count page views and understand which features get used. It does not build a profile of you or follow you to other sites.'
            : 'None. There are no analytics, no tracking pixels, no advertising scripts and no cookies of any kind on this site today.'}
        </p>
        <p>
          Our hosting provider may keep standard server logs — IP address, browser type,
          timestamp — as almost every web host does. This is routine infrastructure logging
          used for security and reliability, not something we read or analyse.
        </p>
        {!ANALYTICS_ENABLED && (
          <p>
            If analytics are added later, this page will be updated before they go live, and
            we will choose a tool that does not use cookies or track you across other sites.
          </p>
        )}
      </Section>

      <Section title="Third parties">
        <p>
          Roadmaps are generated by <strong className="text-ink font-medium">Google Gemini</strong>.
          When you press the button, the text of your answers is sent to Google&rsquo;s API so
          the model can respond. Google&rsquo;s handling of that request is governed by their
          own terms, not ours — see the{' '}
          <a
            href="https://policies.google.com/privacy"
            target="_blank"
            rel="noreferrer noopener"
            className="text-saffron underline underline-offset-2"
          >
            Google Privacy Policy
          </a>{' '}
          and{' '}
          <a
            href="https://ai.google.dev/gemini-api/terms"
            target="_blank"
            rel="noreferrer noopener"
            className="text-saffron underline underline-offset-2"
          >
            Gemini API terms
          </a>
          .
        </p>
        <p>
          Practical advice that applies to any AI tool, including this one: don&rsquo;t type
          anything into the box you would not be comfortable sending to a third-party company.
          It only needs a career name — it does not need your phone number, your marks, your
          address or your full name.
        </p>
      </Section>

      <Section title="Children">
        <p>
          This site is aimed at students finishing Class 10 and Class 12, so many visitors will
          be under 18. That is exactly why it collects nothing: there are no accounts, no
          profiles and no personal details requested at any point.
        </p>
      </Section>

      <Section title="Your rights">
        <p>
          Rights over personal data — access, correction, deletion — generally require someone
          to be holding your data. We hold none, so there is nothing on our side to export or
          erase. The only stored data is the cache on your own device, which you can inspect in
          your browser&rsquo;s developer tools and delete with the button above at any time.
          If you believe any of that is wrong, email us and we will answer honestly.
        </p>
      </Section>

      <Section title="Changes and contact">
        <p>
          If this policy changes in a way that affects what is collected, the date at the top
          will change and the new terms will apply from that date.
        </p>
        <p>
          Questions about privacy:{' '}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-saffron underline underline-offset-2"
          >
            {CONTACT_EMAIL}
          </a>
        </p>
      </Section>
    </PageShell>
  )
}
