import PageShell, { Callout, Section } from '../components/PageShell'
import { CONTACT_EMAIL, LAST_UPDATED } from '../siteConfig'

export default function Terms() {
  return (
    <PageShell
      eyebrow="terms & conditions"
      title="The boring page, minus the boring"
      intro="Nobody reads these. We wrote it like a human anyway, because the bits that actually matter genuinely matter."
      meta={`Last updated ${LAST_UPDATED}`}
    >
      <Callout tone="coral" title="if you read nothing else, read this">
        <p>
          A roadmap here is <strong>written by an AI</strong> and can be confidently, fluently
          wrong. Exam dates move. Eligibility rules change. Cutoffs from last year are not
          cutoffs from this year.
        </p>
        <p>
          Before you act on any step — before you pick a stream, skip an exam or pay anyone
          money — verify it on the official website of the board, exam authority or college.
          Every time. This is the one rule that can actually cost you a year.
        </p>
      </Callout>

      <Section title="1. The deal">
        <p>
          PathFinder is free. There is no subscription, no “premium roadmap tier”, no free
          trial that quietly starts charging you in 7 days. You use it, you get a roadmap, you
          leave. That is the entire business model, such as it is.
        </p>
        <p>
          In exchange, it is provided “as is” — meaning we make no promise that it will be
          available, accurate, or working at 2am the night before your form deadline.
        </p>
      </Section>

      <Section title="2. It is a robot, not a career counsellor">
        <p>
          The roadmaps are generated by an AI model. It is good at structure and genuinely
          useful for seeing the shape of a path. It is not a licensed counsellor, not your
          teacher, and not a person who knows your marks, your budget, your family situation or
          your state&rsquo;s quota rules.
        </p>
        <p>
          Nothing here is professional educational, legal, financial or career advice. It is a
          well-organised starting point for your own research. Please also talk to actual
          humans who know you.
        </p>
      </Section>

      <Section title="3. Please do not sue us over a stream choice">
        <p>
          Said properly: to the fullest extent permitted by law, we accept no liability for any
          loss, missed deadline, rejected application, wasted year or career outcome arising
          from your use of this site.
        </p>
        <p>
          Said plainly: you are the one making the decision. We are handing you a map with a
          visible “check this yourself” label on it. If the map is wrong and you did not check,
          that is a bad outcome for both of us, but it is your decision and your consequence.
        </p>
      </Section>

      <Section title="4. Use it like a reasonable person">
        <p>
          Do: use it, share it, print it, send it to a confused cousin, screenshot it into the
          group chat.
        </p>
        <p>
          Don&rsquo;t: hammer it with automated scripts, try to break it, scrape it wholesale,
          resell it as your own product, or use it to generate content that is illegal or
          harmful. If the site starts falling over because of someone&rsquo;s bot, we reserve
          the right to block access.
        </p>
      </Section>

      <Section title="5. Your roadmap is yours">
        <p>
          Whatever the tool generates for you, you can keep and use freely — save it, print it,
          share it, ignore it entirely. We claim nothing over it.
        </p>
        <p>
          The site itself — the name, the design, the code, the writing — belongs to us. Enjoy
          it, don&rsquo;t clone it wholesale.
        </p>
      </Section>

      <Section title="6. Things may change">
        <p>
          Features may be added, changed or quietly removed. The site may go down for a while,
          or permanently, without notice. If these terms change materially, the date at the top
          of this page changes with them.
        </p>
      </Section>

      <Section title="7. By using this, you agree">
        <p>
          Using PathFinder means you accept these terms. If you don&rsquo;t, that is completely
          fine — close the tab and no hard feelings.
        </p>
        <p>
          If something here seems unfair or unclear, tell us:{' '}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="text-saffron underline underline-offset-2"
          >
            {CONTACT_EMAIL}
          </a>
          . We would rather fix the wording than argue about it later.
        </p>
      </Section>
    </PageShell>
  )
}
