/**
 * UI copy in English and Hindi. Keys missing from `hi` fall back to English, so a new string
 * never renders blank. `{name}` placeholders are filled by `t(key, { name })`.
 *
 * The legal pages (About, Privacy, Terms, Contact) stay English-only on purpose — a loose
 * translation of a privacy policy is worse than none.
 */
export const STRINGS = {
  en: {
    'nav.compare': 'Compare',
    'nav.saved': 'Saved',
    'nav.home': 'PathFinder home',
    'toggle.lang': 'हिंदी में देखें',
    'toggle.langShort': 'हि',
    'toggle.dark': 'Switch to dark mode',
    'toggle.light': 'Switch to light mode',

    'common.back': 'back',
    'common.backHome': 'back to PathFinder',
    'common.savePdf': 'Save as PDF',

    'landing.eyebrow': 'for students after 10th & 12th',
    'landing.h1a': 'Everyone gives advice.',
    'landing.h1b': 'Nobody gives you the steps.',
    'landing.intro':
      'Stream choices, entrance exams, cutoffs — the information is scattered across a hundred tabs and conflicting opinions. PathFinder turns it into one clear path.',
    'landing.fwdTag': 'explore',
    'landing.fwdTitle': 'I don’t know what to pick',
    'landing.fwdBody':
      'Tell us where you are and what you enjoy. We’ll suggest a direction and the route to it.',
    'landing.fwdCta': 'Start here',
    'landing.revTag': 'target',
    'landing.revTitle': 'I already know my dream career',
    'landing.revBody':
      'Name it — pilot, CA, doctor, designer — and get the stream, exams and degrees in order.',
    'landing.revCta': 'Build my path',
    'landing.noSignup': 'no sign-up · takes under a minute',
    'landing.stuck': 'Already stuck between a few options?',
    'landing.compareLink': 'Compare them side by side',
    'landing.how': 'how it works',
    'landing.how1t': 'Answer two questions',
    'landing.how1d': 'Your stage and your interests, or just the career you want.',
    'landing.how2t': 'We map the route',
    'landing.how2d': 'Streams, entrance exams and degrees, in the order they happen.',
    'landing.how3t': 'Save it & share it',
    'landing.how3d': 'Keep it on this device, tick off milestones, or send it to family.',
    'landing.savedCount': 'You have {count} saved roadmap(s)',
    'landing.savedOpen': 'Open them',

    'fwd.step': 'Step {n} of 2',
    'fwd.ready': 'ready',
    'fwd.progress': 'in progress',
    'fwd.title': 'Where are you right now?',
    'fwd.stageLabel': 'Step 1 · Your stage',
    'fwd.stage10': 'Just finished 10th',
    'fwd.stage10hint': 'Choosing a stream next',
    'fwd.stage12': 'Just finished 12th',
    'fwd.stage12hint': 'Choosing a degree next',
    'fwd.interestLabel': 'Step 2 · What interests you',
    'fwd.selected': '{count} selected',
    'fwd.optional': 'optional',
    'fwd.submit': 'Show my roadmap',
    'fwd.pickStage': 'Pick your stage to continue',
    'interest.Math & Logic': 'Math & Logic',
    'interest.Science & Experiments': 'Science & Experiments',
    'interest.Business & Money': 'Business & Money',
    'interest.Art & Design': 'Art & Design',
    'interest.Writing & Communication': 'Writing & Communication',
    'interest.People & Helping others': 'People & Helping others',
    'interest.Computers & Tech': 'Computers & Tech',
    'interest.Not sure yet': 'Not sure yet',

    'rev.eyebrow': 'the destination',
    'rev.title': 'What do you want to become?',
    'rev.body': 'Anything specific works — we’ll work backwards to the stream you should pick.',
    'rev.placeholder': 'e.g. Commercial Pilot',
    'rev.aria': 'Career you want to pursue',
    'rev.common': 'or start from a common one',
    'rev.submit': 'Build my roadmap',

    'loading.title': 'Building your roadmap',
    'loading.m1': 'Reading your answers…',
    'loading.m2': 'Mapping streams and entrance exams…',
    'loading.m3': 'Checking realistic timelines…',
    'loading.m4': 'Laying out your steps…',

    'error.eyebrow': 'that didn’t work',
    'error.title': 'We couldn’t build your roadmap.',
    'error.fallback': 'Something went wrong on the way to the roadmap service.',
    'error.retry': 'Try again',
    'error.restart': 'Start over',

    'roadmap.eyebrow': 'your roadmap',
    'roadmap.steps': '{count} milestones',
    'roadmap.exams': '{count} exams to track',
    'roadmap.fwdFlow': 'interests → career',
    'roadmap.revFlow': 'career → path',
    'roadmap.start': 'You are here',
    'roadmap.startFwd10': 'Class 10 done — choosing a stream',
    'roadmap.startFwd12': 'Class 12 done — choosing a degree',
    'roadmap.startRev': 'About to choose your 11th stream',
    'roadmap.startGeneric': 'The starting line',
    'roadmap.destination': 'Destination',
    'roadmap.milestone': 'Milestone {n}',
    'roadmap.markDone': 'Mark done',
    'roadmap.done': 'Done',
    'roadmap.progress': '{done} of {total} milestones done',
    'roadmap.progressHint': 'Tick milestones as you clear them.',
    'roadmap.progressSaveHint': 'Save this roadmap to keep your progress.',
    'roadmap.examsTitle': 'Checkpoints — exams to watch',
    'roadmap.mistakeTitle': 'Caution — the mistake most people make',
    'roadmap.again': 'Map another path',
    'roadmap.disclaimer':
      'AI-generated guidance — always confirm exam dates and eligibility on official sites.',
    'roadmap.save': 'Save',
    'roadmap.saved': 'Saved',
    'roadmap.unsaveAria': 'Remove from saved roadmaps',
    'roadmap.translate': 'This roadmap is in English.',
    'roadmap.translateCta': 'Get it in Hindi',
    'roadmap.translateEn': 'This roadmap is in Hindi.',
    'roadmap.translateEnCta': 'Get it in English',

    'share.button': 'Share',
    'share.copy': 'Copy link',
    'share.copied': 'Link copied',
    'share.whatsapp': 'WhatsApp',
    'share.failed': 'Couldn’t create a link',
    'share.text': 'My career roadmap from PathFinder: {title}',

    'saved.eyebrow': 'your garage',
    'saved.title': 'Saved roadmaps',
    'saved.intro':
      'Roadmaps you save live on this device only — no account, nothing uploaded. Clearing site data removes them.',
    'saved.empty': 'Nothing saved yet.',
    'saved.emptyBody': 'Build a roadmap and hit “Save” to keep it here.',
    'saved.emptyCta': 'Build a roadmap',
    'saved.open': 'Open',
    'saved.remove': 'Remove',
    'saved.removeAria': 'Remove {title}',
    'saved.on': 'saved {date}',
    'saved.progress': '{done}/{total} done',
    'saved.back': 'all saved roadmaps',
    'saved.missing': 'This saved roadmap isn’t on this device any more.',

    'shared.eyebrow': 'shared with you',
    'shared.bad': 'This share link looks broken or incomplete.',
    'shared.badBody': 'Ask whoever sent it to copy the link again — the whole thing, end to end.',
    'shared.makeOwn': 'Make your own roadmap',

    'compare.back': 'back to PathFinder',
    'compare.change': 'change options',
    'compare.eyebrow': 'compare',
    'compare.title': 'B.Tech or B.Sc or BCA?',
    'compare.intro':
      'Pick two to four options and see them side by side — duration, eligibility, exams, salary and what each one actually leads to.',
    'compare.selection': 'Your selection',
    'compare.of': '{count} of {max}',
    'compare.none': 'Nothing picked yet — choose at least two below.',
    'compare.remove': 'Remove {name}',
    'compare.group.Degrees': 'Degrees',
    'compare.group.Diplomas': 'Diplomas',
    'compare.group.Careers': 'Careers',
    'compare.else': 'Something else',
    'compare.placeholder': 'e.g. B.Pharm',
    'compare.addAria': 'Add another option to compare',
    'compare.add': 'Add',
    'compare.pickTwo': 'Pick at least two to compare',
    'compare.run': 'Compare {count} options',
    'compare.sideBySide': 'side by side',
    'compare.salaryTitle': 'about those salary figures',
    'compare.salaryBody':
      'These are indicative ranges, not promises. Actual pay swings hugely with your college tier, city, company and skills — two people with the same degree can earn very differently. Treat them as rough scale, and check current figures on job sites before making a decision on money alone.',
    'compare.choose': 'How to actually choose',
    'compare.again': 'Compare something else',
    'compare.disclaimer':
      'AI-generated comparison — confirm eligibility and fees on official college sites.',
    'row.kind': 'Type',
    'row.duration': 'Duration',
    'row.eligibility': 'Eligibility',
    'row.entranceExams': 'Entrance exams',
    'row.studyFocus': 'What you study',
    'row.startingSalary': 'Starting salary',
    'row.experiencedSalary': 'After 5–8 years',
    'row.topRoles': 'Common roles',
    'row.higherStudies': 'Higher studies',
    'row.bestFor': 'Best suited to',
    'row.watchOut': 'Watch out for',

    'footer.tagline': 'PathFinder — clear next steps after Class 10 & 12',
    'footer.disclaimer':
      'Roadmaps are AI-generated. Always confirm exam dates and eligibility on official sites.',
    'footer.about': 'About',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.contact': 'Contact',

    'notfound.title': 'This path doesn’t exist.',
    'notfound.body':
      'Ironic, for a site about finding the right route. The page you were looking for isn’t here.',
    'notfound.cta': 'Back to the start',
  },

  hi: {
    'nav.compare': 'तुलना',
    'nav.saved': 'सेव्ड',
    'nav.home': 'PathFinder होम',
    'toggle.lang': 'View in English',
    'toggle.langShort': 'EN',
    'toggle.dark': 'डार्क मोड चालू करें',
    'toggle.light': 'लाइट मोड चालू करें',

    'common.back': 'वापस',
    'common.backHome': 'PathFinder पर वापस',
    'common.savePdf': 'PDF में सेव करें',

    'landing.eyebrow': '10वीं और 12वीं के बाद के छात्रों के लिए',
    'landing.h1a': 'सलाह सब देते हैं।',
    'landing.h1b': 'रास्ता कोई नहीं बताता।',
    'landing.intro':
      'स्ट्रीम, एंट्रेंस एग्ज़ाम, कटऑफ़ — जानकारी सौ टैब्स और अलग-अलग रायों में बिखरी है। PathFinder उसे एक साफ़ रास्ते में बदल देता है।',
    'landing.fwdTag': 'खोजें',
    'landing.fwdTitle': 'मुझे नहीं पता क्या चुनूँ',
    'landing.fwdBody':
      'बताइए आप अभी कहाँ हैं और आपको क्या पसंद है। हम एक दिशा और वहाँ तक का रास्ता सुझाएँगे।',
    'landing.fwdCta': 'यहाँ से शुरू करें',
    'landing.revTag': 'लक्ष्य',
    'landing.revTitle': 'मुझे अपना ड्रीम करियर पता है',
    'landing.revBody':
      'करियर का नाम लिखें — पायलट, CA, डॉक्टर, डिज़ाइनर — और स्ट्रीम, एग्ज़ाम और डिग्री सही क्रम में पाएँ।',
    'landing.revCta': 'मेरा रास्ता बनाएँ',
    'landing.noSignup': 'कोई साइन-अप नहीं · एक मिनट से कम',
    'landing.stuck': 'कुछ ऑप्शन्स के बीच उलझे हैं?',
    'landing.compareLink': 'उनकी साथ-साथ तुलना करें',
    'landing.how': 'यह कैसे काम करता है',
    'landing.how1t': 'दो सवालों के जवाब दें',
    'landing.how1d': 'आपकी क्लास और रुचियाँ, या सिर्फ़ वह करियर जो आप चाहते हैं।',
    'landing.how2t': 'हम रास्ता बनाते हैं',
    'landing.how2d': 'स्ट्रीम, एंट्रेंस एग्ज़ाम और डिग्री — जिस क्रम में वे आते हैं।',
    'landing.how3t': 'सेव करें और शेयर करें',
    'landing.how3d': 'इस डिवाइस पर रखें, पड़ाव टिक करें, या घरवालों को भेजें।',
    'landing.savedCount': 'आपके {count} रोडमैप सेव हैं',
    'landing.savedOpen': 'खोलें',

    'fwd.step': 'स्टेप {n} / 2',
    'fwd.ready': 'तैयार',
    'fwd.progress': 'जारी है',
    'fwd.title': 'आप अभी कहाँ हैं?',
    'fwd.stageLabel': 'स्टेप 1 · आपकी क्लास',
    'fwd.stage10': 'अभी 10वीं पूरी की है',
    'fwd.stage10hint': 'आगे स्ट्रीम चुननी है',
    'fwd.stage12': 'अभी 12वीं पूरी की है',
    'fwd.stage12hint': 'आगे डिग्री चुननी है',
    'fwd.interestLabel': 'स्टेप 2 · आपकी रुचि',
    'fwd.selected': '{count} चुने गए',
    'fwd.optional': 'वैकल्पिक',
    'fwd.submit': 'मेरा रोडमैप दिखाएँ',
    'fwd.pickStage': 'आगे बढ़ने के लिए अपनी क्लास चुनें',
    'interest.Math & Logic': 'गणित और लॉजिक',
    'interest.Science & Experiments': 'विज्ञान और प्रयोग',
    'interest.Business & Money': 'बिज़नेस और पैसा',
    'interest.Art & Design': 'आर्ट और डिज़ाइन',
    'interest.Writing & Communication': 'लेखन और कम्युनिकेशन',
    'interest.People & Helping others': 'लोगों की मदद करना',
    'interest.Computers & Tech': 'कंप्यूटर और टेक',
    'interest.Not sure yet': 'अभी पक्का नहीं',

    'rev.eyebrow': 'मंज़िल',
    'rev.title': 'आप क्या बनना चाहते हैं?',
    'rev.body': 'कुछ भी लिखें — हम पीछे की ओर चलकर बताएँगे कि कौन-सी स्ट्रीम चुननी है।',
    'rev.placeholder': 'जैसे Commercial Pilot',
    'rev.aria': 'जो करियर आप चाहते हैं',
    'rev.common': 'या इनमें से चुनें',
    'rev.submit': 'मेरा रोडमैप बनाएँ',

    'loading.title': 'आपका रोडमैप बन रहा है',
    'loading.m1': 'आपके जवाब पढ़ रहे हैं…',
    'loading.m2': 'स्ट्रीम और एंट्रेंस एग्ज़ाम देख रहे हैं…',
    'loading.m3': 'सही टाइमलाइन जाँच रहे हैं…',
    'loading.m4': 'आपके स्टेप्स तैयार कर रहे हैं…',

    'error.eyebrow': 'कुछ गड़बड़ हुई',
    'error.title': 'हम आपका रोडमैप नहीं बना पाए।',
    'error.fallback': 'रोडमैप सर्विस तक पहुँचते समय कुछ गलत हो गया।',
    'error.retry': 'फिर से कोशिश करें',
    'error.restart': 'शुरू से करें',

    'roadmap.eyebrow': 'आपका रोडमैप',
    'roadmap.steps': '{count} पड़ाव',
    'roadmap.exams': '{count} एग्ज़ाम पर नज़र',
    'roadmap.fwdFlow': 'रुचि → करियर',
    'roadmap.revFlow': 'करियर → रास्ता',
    'roadmap.start': 'आप यहाँ हैं',
    'roadmap.startFwd10': '10वीं पूरी — स्ट्रीम चुननी है',
    'roadmap.startFwd12': '12वीं पूरी — डिग्री चुननी है',
    'roadmap.startRev': '11वीं की स्ट्रीम चुनने वाले हैं',
    'roadmap.startGeneric': 'शुरुआत',
    'roadmap.destination': 'मंज़िल',
    'roadmap.milestone': 'पड़ाव {n}',
    'roadmap.markDone': 'पूरा हुआ',
    'roadmap.done': 'पूरा',
    'roadmap.progress': '{total} में से {done} पड़ाव पूरे',
    'roadmap.progressHint': 'जो पड़ाव पार कर लें, उन्हें टिक करें।',
    'roadmap.progressSaveHint': 'प्रोग्रेस बचाने के लिए यह रोडमैप सेव करें।',
    'roadmap.examsTitle': 'चेकपॉइंट — इन एग्ज़ाम पर नज़र रखें',
    'roadmap.mistakeTitle': 'सावधान — ज़्यादातर लोग यह गलती करते हैं',
    'roadmap.again': 'दूसरा रास्ता बनाएँ',
    'roadmap.disclaimer':
      'यह AI से बनी जानकारी है — एग्ज़ाम की तारीख़ और योग्यता हमेशा आधिकारिक साइट पर जाँचें।',
    'roadmap.save': 'सेव करें',
    'roadmap.saved': 'सेव हो गया',
    'roadmap.unsaveAria': 'सेव्ड रोडमैप से हटाएँ',
    'roadmap.translate': 'यह रोडमैप अंग्रेज़ी में है।',
    'roadmap.translateCta': 'हिंदी में बनाएँ',
    'roadmap.translateEn': 'यह रोडमैप हिंदी में है।',
    'roadmap.translateEnCta': 'अंग्रेज़ी में बनाएँ',

    'share.button': 'शेयर',
    'share.copy': 'लिंक कॉपी करें',
    'share.copied': 'लिंक कॉपी हो गया',
    'share.whatsapp': 'WhatsApp',
    'share.failed': 'लिंक नहीं बन पाया',
    'share.text': 'PathFinder से मेरा करियर रोडमैप: {title}',

    'saved.eyebrow': 'आपका संग्रह',
    'saved.title': 'सेव किए गए रोडमैप',
    'saved.intro':
      'सेव किए गए रोडमैप सिर्फ़ इसी डिवाइस पर रहते हैं — कोई अकाउंट नहीं, कुछ अपलोड नहीं होता। साइट डेटा साफ़ करने पर ये हट जाएँगे।',
    'saved.empty': 'अभी कुछ सेव नहीं है।',
    'saved.emptyBody': 'एक रोडमैप बनाइए और “सेव करें” दबाइए।',
    'saved.emptyCta': 'रोडमैप बनाएँ',
    'saved.open': 'खोलें',
    'saved.remove': 'हटाएँ',
    'saved.removeAria': '{title} हटाएँ',
    'saved.on': '{date} को सेव किया',
    'saved.progress': '{done}/{total} पूरे',
    'saved.back': 'सभी सेव्ड रोडमैप',
    'saved.missing': 'यह सेव किया गया रोडमैप अब इस डिवाइस पर नहीं है।',

    'shared.eyebrow': 'आपके साथ शेयर किया गया',
    'shared.bad': 'यह शेयर लिंक टूटा हुआ या अधूरा लग रहा है।',
    'shared.badBody': 'भेजने वाले से पूरा लिंक दोबारा कॉपी करके भेजने को कहें।',
    'shared.makeOwn': 'अपना रोडमैप बनाएँ',

    'compare.back': 'PathFinder पर वापस',
    'compare.change': 'ऑप्शन बदलें',
    'compare.eyebrow': 'तुलना',
    'compare.title': 'B.Tech, B.Sc या BCA?',
    'compare.intro':
      'दो से चार ऑप्शन चुनें और साथ-साथ देखें — अवधि, योग्यता, एग्ज़ाम, सैलरी और हर एक से आगे क्या मिलता है।',
    'compare.selection': 'आपका चुनाव',
    'compare.of': '{max} में से {count}',
    'compare.none': 'अभी कुछ नहीं चुना — नीचे से कम से कम दो चुनें।',
    'compare.remove': '{name} हटाएँ',
    'compare.group.Degrees': 'डिग्री',
    'compare.group.Diplomas': 'डिप्लोमा',
    'compare.group.Careers': 'करियर',
    'compare.else': 'कुछ और',
    'compare.placeholder': 'जैसे B.Pharm',
    'compare.addAria': 'तुलना के लिए और ऑप्शन जोड़ें',
    'compare.add': 'जोड़ें',
    'compare.pickTwo': 'तुलना के लिए कम से कम दो चुनें',
    'compare.run': '{count} ऑप्शन की तुलना करें',
    'compare.sideBySide': 'साथ-साथ',
    'compare.salaryTitle': 'सैलरी के आँकड़ों के बारे में',
    'compare.salaryBody':
      'ये सिर्फ़ अनुमानित रेंज हैं, वादे नहीं। असली सैलरी कॉलेज, शहर, कंपनी और स्किल्स के हिसाब से बहुत बदलती है — एक ही डिग्री वाले दो लोग बहुत अलग कमा सकते हैं। इन्हें मोटा अंदाज़ा मानें और सिर्फ़ पैसे के आधार पर फ़ैसला लेने से पहले जॉब साइट्स पर मौजूदा आँकड़े देखें।',
    'compare.choose': 'असल में कैसे चुनें',
    'compare.again': 'कुछ और तुलना करें',
    'compare.disclaimer':
      'यह AI से बनी तुलना है — योग्यता और फ़ीस कॉलेज की आधिकारिक साइट पर जाँचें।',
    'row.kind': 'प्रकार',
    'row.duration': 'अवधि',
    'row.eligibility': 'योग्यता',
    'row.entranceExams': 'एंट्रेंस एग्ज़ाम',
    'row.studyFocus': 'क्या पढ़ेंगे',
    'row.startingSalary': 'शुरुआती सैलरी',
    'row.experiencedSalary': '5–8 साल बाद',
    'row.topRoles': 'आम जॉब रोल',
    'row.higherStudies': 'आगे की पढ़ाई',
    'row.bestFor': 'किसके लिए सही',
    'row.watchOut': 'ध्यान रखें',

    'footer.tagline': 'PathFinder — 10वीं और 12वीं के बाद के साफ़ अगले कदम',
    'footer.disclaimer':
      'रोडमैप AI से बनते हैं। एग्ज़ाम की तारीख़ और योग्यता हमेशा आधिकारिक साइट पर जाँचें।',
    'footer.about': 'About',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms & Conditions',
    'footer.contact': 'Contact',

    'notfound.title': 'यह रास्ता मौजूद नहीं है।',
    'notfound.body': 'सही रास्ता ढूँढने वाली साइट पर यह थोड़ा अजीब है। आप जो पेज ढूँढ रहे थे, वह यहाँ नहीं है।',
    'notfound.cta': 'शुरुआत पर वापस',
  },
}
